# fly.toml app configuration file generated for voiceprint on 2026-04-26T20:11:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voiceprint'
primary_region = 'ord'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 5
    soft_limit = 2

[[vm]]
  size = 'shared-cpu-1x'
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
